# Generated by Django 5.0.3 on 2024-04-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_paid',
            new_name='payment_method',
        ),
    ]
